### ISSUE TITLE
Community tooling candidates

### ISSUE THREAD

**Issue by RVR06** [structurizr/structurizr.github.io#23]
### Question

Hi @simonbrowndotje,

I recently disclosed [a bootcamp of mine](https://rvr06.github.io/c4-bootcamp/), focusing on code-first approach to model software architecture the C4 way. It leverages `Structurizr DSL` for authoring - for which I also crafted a dedicated VS Code extension, aka [Cornifer](https://rvr06.github.io/cornifer/) - and dockerized `Structurizr Lite` for rendering.

Bootcamp is a self-directed one adopting a **from zero to hero** approach by unfolding a compelling software, covering most of the C4 model traits with both hands-on section and explanation of the underlying intent.

![image](https://github.com/user-attachments/assets/1a9ffee5-d246-4a66-a706-bf94fcca4ce1)

![image](https://github.com/user-attachments/assets/9e45190b-1e83-4c2d-bd2e-53d4bec22758)

Bootcamp comes with a companion website which compiles thoughts and materials I am using to introduce software architecture.

![image](https://github.com/user-attachments/assets/8ede65c3-8120-4c3b-8b9a-61de4f2688bb)

Cornifer is the VS Code extension I ended up with to support my journey. It comes with some [features](https://rvr06.github.io/cornifer/docs/features/) I did not find back in time in available tooling and may be of interest as well for code-first aficionado.

![image](https://github.com/user-attachments/assets/0288b685-d1f2-4d3b-add0-845a5fd18988)

Both bootcamp and extension could benefit of being listed in the community tooling and being exercised by more people to feed the C4 ecosystem.

Feel free to touch base if you need more information.

Romain

**Comment by amirulmenjeni** [comment]
Very cool project. I've had my fair share of frustrations with the [C4 DSL Extension by systemticks](https://marketplace.visualstudio.com/items?itemName=systemticks.c4-dsl-extension). 

For example:
- The language server doesn't seem to work while editing `.dsl` file that are meant to be `!include`ed from another `.dsl` file that defines the workspace. This is probably because the `.dsl` files doesn't have `workspace` token in it. Poor support for working on modular `.dsl` codes in general.
- Sometimes language server fails. The autocompletion/autosuggestion sometimes just stopped working -- and there's no command in VS Code to manually restart the language server. When this happens, I had to restart VS Code.
- Some errors aren't caught by the language server, and are only caught during building/publishing.

Will try this out when I get the chance.

**Comment by simonbrowndotje** [comment]
Thanks!
